services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    volumes:
      - "/opt/pgdata:/var/lib/postgresql/data/"